### ISSUE TITLE
Re-establish a GPU-based CI

### ISSUE THREAD

**Issue by huitseeker** [lurk-lab/neptune#180]
We introduced basic CI as part of #177 to compensate for the change in CI infrastructure. We should introduce a Docker runner able to test Neptune CI with OpenCL and CUDA capabilities, and then run it in the form of self-hosted runners.

To achieve this, we need to integrate the following resources:

- Existing CI: We currently have a CI pipeline set up with GitHub Actions.

- Self-Hosted Runner Documentation: The official GitHub documentation for self-hosted runners can be found here: https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners and https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow

- NVIDIA Container Toolkit: In order to use the GPU within our Docker container, we can integrate the NVIDIA Container Toolkit (https://github.com/NVIDIA/nvidia-docker) into our setup.

- Dockerfile Example: A sample Dockerfile that demonstrates basic Rust installation: https://gist.github.com/huitseeker/0c58ee69f63c5e81d6ea64f0dc5153f7. This example can serve as a starting point for our own Dockerfile configuration.

**Comment by vmx** [comment]
> * NVIDIA Container Toolkit: In order to use the GPU within our Docker container, we can integrate the NVIDIA Container Toolkit (https://github.com/NVIDIA/nvidia-docker) into our setup.

I know that you use GitHub actions, though it might still be helpful to see the NVIDIA docker images in action. I use them in a CircleCI confi here: https://github.com/filecoin-project/rust-filecoin-proofs-api/blob/73de3fa31b5c22e6389bb220648b2becf6caab05/.circleci/config.yml#L13

**Comment by huitseeker** [comment]
Notes for @samuelburnham / @winston-h-zhang  :
- in order to run a rust job on a suitably equipped GPU machine, one conceptually needs to run the normal suite of tests, with the features to test the appropriate compiler suite.
- those compilers suites are the cuda suite (rust -> cuda -> gpu) and the opencl suite (rust -> opencl -> cuda -> gpu) on a machine equipped with an NVidia GPU. There are matching features for each in all the GPU dependent rust projects in our stack (bellperson, ec-gpu, neptune, lurk-rs), and the dependent projects activate the dependee’s features transitively,
- besides running the builds & tests with those features, we also want to set a few key environment variables for ec-gpu to do its job sensibly:
`EC_GPU_CUDA_NVCC_ARGS`, which value is hardware-dependent (look up your architecture and compute capability by looking up your GPU model in Nvidia’s doc) and `EC_GPU_FRAMEWORK`, which is « cuda » or «  opencl » depending on the pipeline you are testing.
Those are documented in ec-gpu’s doc:
https://github.com/filecoin-project/ec-gpu#environment-variables

See also the point at which the former is set in our build (but remember you may be in a context where your physical GPU is different):
https://github.com/lurk-lab/neptune/blob/master/.circleci/config.yml#L92
